spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns: '*'
            allowed-headers: '*'
            allowed-methods: '*'

      routes:
        - id: order-route
          uri: lb://service-order #lb负载均衡
          predicates:
            - name: Path
              args:
                patterns: /api/order/**
                matchTrailingSlash: true
          filters: #/api/order/ab/c 改写为/ab/c
            - RewritePath=/api/order/?(?<segment>.*),/$\{segment}
            - OnceToken=X-Response-Token,uuid


        - id: product-route
          uri: lb://product-route
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/product/?(?<segment>.*),/$\{segment}

        - id: bing-route
          uri: https://cn.bing.com/
          predicates:
            - name: Path
              args:
                patterns: /search
            - name: Query
              args:
                param: q
                regexp: haha
                #必须/search 带参数q值为haha才转发
            - Vip=user,baiyaoshi
      default-filters:
        - AddResponseHeader=X-response,11111

